apiVersion: v1
kind: Service
metadata:
  name: chat-ui
  namespace: chat-ui
  labels:
    app: chat-ui
spec:
  type: ClusterIP
  selector:
    app: chat-ui
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
